FILE_SIZE_LIMIT = 10 * 1024 * 1024 
DATA_CHUNK_SIZE_LIMIT = 120 * 1024 * 1024
JOBS_DIRECTORY_PATH = "Jobs"
DEFAULT_PORT = 2222
FUNC_FOOTPRINT_FILE = "func_lines_footprint.json"
MAIN_FOOTPRINT_FILE = "main_lines_footprint.json"
MAIN_LISTS_FILE = "main_lists.json"