# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0eproject_common\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x44\x61taIdentifier\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x03\"\x1c\n\x0e\x46ileIdentifier\x12\n\n\x02id\x18\x01 \x01(\x03\"\xa3\x01\n\x0c\x44\x61taMetadata\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x03\x12\x11\n\tdata_name\x18\x02 \x01(\t\x12\x18\n\x10total_size_bytes\x18\x03 \x01(\x03\x12\x12\n\nip_address\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x0c\n\x04hash\x18\x06 \x01(\t\x12\x14\n\x0cis_on_master\x18\x07 \x01(\x08\x12\x0f\n\x07task_id\x18\x08 \x01(\x03\"6\n\tDataChunk\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x15\n\ris_last_chunk\x18\x02 \x01(\x08\"[\n\x08\x44\x61taInfo\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x03\x12\x0f\n\x07task_id\x18\x02 \x01(\x03\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\t\x12\x0c\n\x04hash\x18\x05 \x01(\t*V\n\x08\x44\x61taType\x12\x19\n\x15\x44\x41TA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x44\x41TA_TYPE_FILE\x10\x01\x12\x1b\n\x17\x44\x41TA_TYPE_PYTHON_PICKLE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=464
  _globals['_DATATYPE']._serialized_end=550
  _globals['_STATUSRESPONSE']._serialized_start=32
  _globals['_STATUSRESPONSE']._serialized_end=82
  _globals['_DATAIDENTIFIER']._serialized_start=84
  _globals['_DATAIDENTIFIER']._serialized_end=117
  _globals['_FILEIDENTIFIER']._serialized_start=119
  _globals['_FILEIDENTIFIER']._serialized_end=147
  _globals['_DATAMETADATA']._serialized_start=150
  _globals['_DATAMETADATA']._serialized_end=313
  _globals['_DATACHUNK']._serialized_start=315
  _globals['_DATACHUNK']._serialized_end=369
  _globals['_DATAINFO']._serialized_start=371
  _globals['_DATAINFO']._serialized_end=462
# @@protoc_insertion_point(module_scope)
