# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\nmaster_api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"(\n\x15NodeUnregisterRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x03\"l\n\x13NodeRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x1b\n\x13machine_fingerprint\x18\x03 \x01(\t\x12\x14\n\x0cmemory_bytes\x18\x04 \x01(\x03\"$\n\x12JobCompleteRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x03\x32\x84\x02\n\rMasterService\x12O\n\x0cNodeRegister\x12\x1f.master_api.NodeRegisterRequest\x1a\x1e.project_common.StatusResponse\x12M\n\x0bJobComplete\x12\x1e.master_api.JobCompleteRequest\x1a\x1e.project_common.StatusResponse\x12S\n\x0eNodeUnregister\x12!.master_api.NodeUnregisterRequest\x1a\x1e.project_common.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEUNREGISTERREQUEST']._serialized_start=71
  _globals['_NODEUNREGISTERREQUEST']._serialized_end=111
  _globals['_NODEREGISTERREQUEST']._serialized_start=113
  _globals['_NODEREGISTERREQUEST']._serialized_end=221
  _globals['_JOBCOMPLETEREQUEST']._serialized_start=223
  _globals['_JOBCOMPLETEREQUEST']._serialized_end=259
  _globals['_MASTERSERVICE']._serialized_start=262
  _globals['_MASTERSERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
