# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import master_pb2 as master__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in master_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodeRegister = channel.unary_unary(
                '/master_api.MasterService/NodeRegister',
                request_serializer=master__pb2.NodeRegisterRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.JobComplete = channel.unary_unary(
                '/master_api.MasterService/JobComplete',
                request_serializer=master__pb2.JobCompleteRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.NodeUnregister = channel.unary_unary(
                '/master_api.MasterService/NodeUnregister',
                request_serializer=master__pb2.NodeUnregisterRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NodeRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeUnregister(self, request, context):
        """rpc NodeHeartbeat(NodeHeartbeatRequest) returns (NodeHeartbeatResponse);
        rpc JobFailed(JobFailedRequest) returns (JobFailedResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NodeRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeRegister,
                    request_deserializer=master__pb2.NodeRegisterRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'JobComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.JobComplete,
                    request_deserializer=master__pb2.JobCompleteRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'NodeUnregister': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeUnregister,
                    request_deserializer=master__pb2.NodeUnregisterRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'master_api.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('master_api.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NodeRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/master_api.MasterService/NodeRegister',
            master__pb2.NodeRegisterRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/master_api.MasterService/JobComplete',
            master__pb2.JobCompleteRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeUnregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/master_api.MasterService/NodeUnregister',
            master__pb2.NodeUnregisterRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
